name="Silpa"
a=["anwar",["anwar",name]]
print(a[-1][1][1])
v=[10,20,"abc",15,35,15]
print(v[1:5])
print(v[::2])
print(v[:5])
print(v[2:])
print(v[::-1])
nm="SILPA"
print(nm)
print(nm.lower())
n="SILPA"
print(n.upper())
s="anwar sadath"
print(s.count("a"))
print(s.count("a",0,3))
print(s.index("a"))
print(s.find("a",1,5))
print(s.replace("a","z",2))
t="Anwar Sadath"
print(t.swapcase())
print(v[5])
v[5]=20
print(v)
v.append(22)
print(v)
v.append("chingu")
print(v)
v.extend("anwar")
print(v)
k=[5,1,3,10]
k.sort()
print(k)
k.sort(reverse=True)
print(k)
p=[10,20,"abc",15,35,15]
p.insert(6,50)
print(p)
p.pop()
print(p)
p.pop(3)
print(p)
q=[10,20,"abc",15,35,15]
q.remove(15)
print(q)
d={"name":"Silpa","age":"23","marks":"95"}
print(d)
print(d["name"])
d["country"]="India"
print(d)
v=d.get("name")
print(v)
f=d.get("nation","India")
print(f)
h=d.items()
print(h)
e=d.keys()
print(e)
print(d.pop("marks"))
print(d.pop("marks",95))
print(d.setdefault("course","MCA"))
print(d)
c={"dob":"25/10/99","regno":"123456"}
d.update(c)
print(d)
A={1,2,3,1,2,3}
print(A)
w=[1,2,3,1,2,3]
print(w)
print(set(w))
print(list(set(w)))
tup=("Seth","Becky","Dean",2,"Dean")
print(tup)
print(tup[0])
print(list(tup))
l=[10,20,"abc",15,35,15]
print(l[::3])


